### ISSUE TITLE
Add thorough data layer tests

### ISSUE THREAD

**Issue by hodgestar** [qutip/qutip-cupy#16]
The data layer is fundamental to how all operations on QuTiP Qobjs are performed, so we need to be really sure they're correct in all cases.

To achieve this we need to generate tests that thoroughly cover the possible inputs and combinations of dispatch functions. One possible approach / source of ideas is to reuse the test utilities from the data layer itself (see https://github.com/qutip/qutip/blob/dev.major/qutip/tests/core/data/test_mathematics.py).

Another possible approach is to use hypothesis -- see https://hypothesis.readthedocs.io/en/latest/numpy.html.

**Comment by MrRobot2211** [comment]
This has been tackled in #10 .
