### ISSUE TITLE
List of specializations 

### ISSUE THREAD

**Issue by MrRobot2211** [qutip/qutip-cupy#26]
This solves #24 
The titless indicate the state in which they are found in dev.major

dispatched and testesd

- [x]  add
- [x] sub
- [x] mul
- [x] imul
- [x] conj
- [x] adjoint
- [x] transpose

- [x] tidyup

- [x] trace

- [x] inner

- [x] project
- [x] kron

not dispatched but tested
- [x]  iadd

dispatched but untested
- [x] reshape
- [ ] stack
- [ ] unstack

- [x] pow
- [ ] expm

- [x] l2norm
- [x] l1norm
- [x] maxnorm

- [x] expect
- [ ] eigvals
- [x] split_columns (used by Qobj to return the eigenvectors as a list of Qobjs)
- [x] inv (used by taking the sqrt of the Qobj -- not used often, but should be easy to implement)

- [x] isherm (used to check hermicity and might be called regularly, so a priority)

**Comment by hodgestar** [comment]
Almost all of these are implement, except:

* `eigvals` and `expm` which have their own issue (#40)
* and `column_stack` and `column_unstack` (which I am happy to us to just leave until we need them)

Closing this issue.
